Update sentiment_analysis.ipynb
NeuromatchAcademy/course-content-dl pull request #956
Opened 2024-07-05 10:34 UTC by Dammy-Joe

Fixed the broken dataset link and used the iter's next method instead of the next attribute

2024-07-05 20:53 UTC, iamzoltan requested changes
It looks like you are using colab and havent cleared your kernel or cells before saving and creating this PR. Can you spin up jupyter notebook locally? Or clear all cells and the kernel before saving? There are too many artifacts contained in the raw data.

2024-07-05 20:53 UTC, iamzoltan commented on projects/NaturalLanguageProcessing/sentiment_analysis.ipynb
> +        "\n",
What happened to the colab and kaggle links?

2024-07-07 21:01 UTC, iamzoltan commented
@Dammy-Joe Please pull the latest changes to hot-fixes branch, and build your changes off that branch. Also please run jupyter locally and clear all cell and kernel before saving

2024-07-07 21:54 UTC, Dammy-Joe commented
Thanks @iamzoltan. All the required changes to sentiment_analysis.ipynb have been made in hot_fixes. So, there's no need for a pull request.

2024-07-08 03:33 UTC, iamzoltan commented
alright, closing this PR. Let me know if we need to address anything else

2024-07-08 03:33 UTC, closed without merging